// src/components/Project.tsx
import Image from 'next/image';
import Badge from './ui/Badge';
import { Heading } from './ui/Heading';
import Link from 'next/link';

interface ProjectProps {
    project: ProjectItem
}

export default function Project({ project }: ProjectProps) {
    return <>
        <Heading label={project.title} />
        <a href={project.url} target="_blank">
            <Image className="aspect-auto rounded-t-sm" src={project.image} alt={`Screenshot of ${project.title} project`} width="400" height="150" />
        </a>
        <div className="flex flex-col gap-2 bg-black p-2 rounded-b-sm">
            <div className="flex flex-col gap-1">
                <strong className="text-sm">Skills</strong>
                <div className="flex flex-wrap gap-2">
                    {project.skills.map(skill => <Badge key={skill} label={skill} />)}
                </div>
            </div>
            <div className="flex flex-col gap-1">
                <strong className="text-sm">Areas</strong>
                <div className="flex flex-wrap gap-2">
                    {project.areas.map(area => <Badge key={area} label={area} />)}
                </div>
            </div>
            <Link className="btn btn-link text-white" target="_blank" href={project.url}>View Project</Link>
        </div>
    </>;
}

// src/lib/app/components/Project.svelte
<script lang="ts">
    import Badge from './ui/Badge.svelte';
    import Heading from './ui/Heading.svelte';

    export let project: ProjectItem;
</script>

<div class="flex flex-col md:flex-row justify-start gap-2 max-w-6xl mx-auto">
    <div class="flex flex-col gap-2">
        <Heading label={project.title} />
        <a href={project.url} target="_blank">
            <img class="aspect-auto rounded-sm shadow-xl border-1 border-stone-100" src={project.image} alt={`Screenshot of ${project.title} project`} width="400" height="150" />
        </a>
        <div class="flex justify-between items-start">
            <Badge label={project.type}></Badge>
            <a class="px-2 py-1 uppercase text-xs text-white" target="_blank" href={project.url}>View Project</a>
        </div>
    </div>
    <div class="flex flex-col md:w-1/2 gap-2 md:p-2">
        <div class="flex flex-col gap-1 mb-4">
            <strong>Overview</strong>
            <p>{project.description}</p>
        </div>
        <div class="flex flex-col gap-1">
            <strong>Skills</strong>
            <div class="flex flex-wrap gap-2">
                {#each project.skills as skill (skill)}
                    <span class="uppercase text-sm"><span class="text-stone-400">#</span>{skill}</span>
                {/each}
            </div>
        </div>
        <div class="flex flex-col gap-1">
            <strong>Areas</strong>
            <div class="flex flex-wrap gap-2">
                {#each project.areas as area (area)}
                    <span class="uppercase text-sm"><span class="text-stone-400">#</span>{area}</span>
                {/each}
            </div>
        </div>
    </div>
</div>
