// src/components/SiteHeader.tsx
import Image from 'next/image';
import Link from 'next/link';
import LinkedInButton from './buttons/LinkedInButton';
import ResumeButton from './buttons/ResumeButton';

export default function SiteHeader() {
    return <header className="flex flex-col md:flex-row items-center md:justify-between px-4 py-4 md:py-0 border-b border-slate-500">
      <Link href="/">
        <Image src="/img/site-logo.png" alt="imperez logo" width="300" height="86" />
      </Link>
      <nav className="flex gap-2 justify-center">
        <Link className="btn btn-ghost -mt-2 md:my-2" href="/projects">Projects</Link>
        <ResumeButton />
        <LinkedInButton />
      </nav>
    </header>;
}

// src/lib/app/components/SiteHeader.svelte
<header class="flex flex-col md:flex-row items-center md:justify-between px-4 py-4 border-b border-slate-500">
  <a href="/">
    <img src="/img/site-logo.png" alt="site logo" width="300" height="46" />
  </a>
  <nav class="flex gap-2 justify-center">
    <a class="btn btn-link text-white" href="/about">About</a>
    <a class="btn btn-link text-white" href="/colophon">Colophon</a>
    <a class="btn btn-link text-white" href="/uses">Uses</a>
  </nav>
</header>
