// app/projects/page.tsx
import { all } from "@/src/repositories/projects";
import Project from "@/src/components/Project";
import PageHeading from "@/src/components/ui/PageHeading";

export default function Projects() {
    return (
      <section className="flex flex-col gap-4">
        <div className="py-10">
          <PageHeading label="Projects" />
        </div>
        <ol className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {all().map(project => {
            return <li key={project.title}>
              <Project project={project} />
            </li>
          })}
        </ol>
      </section>
    )
}

// src/routes/projects/+page.svelte
<script>
    import Project from "$lib/components/Project.svelte";
    import PageHeading from "$lib/components/ui/PageHeading.svelte";
    import { all } from "$lib/repositories/projects";
</script>

<section class="flex flex-col gap-4">
    <div class="py-10">
      <PageHeading label="Projects" />
    </div>
    <ol class="grid grid-cols-1 md:grid-cols-4 gap-4">
      {#each all() as project (project.title)}
        <li>
          <Project project={project} />
        </li>
      {/each}
    </ol>
</section>
